project: Watchr

build:
  configuration: Debug
  version:
    full: 1.0.0

deployment:
  connection:
    computer_name: localhost
    username: <%= ENV['DEPLOY_USER'] %>
    password: <%= ENV['DEPLOY_PASSWORD'] %>

  remote_path: <%= (File.join(ENV['TEMP'] || '', '_watchr')).gsub(%r|/|, File::ALT_SEPARATOR || File::SEPARATOR) %>

  bindings:
    -
      :protocol: http
      :host: localhost
    -
      :protocol: http
      :host: watchr.dev
      :test_while_deployment: false
