project: Watchr

build:
  configuration: Debug
  metadata:
    pre: alpha<%= ENV['BUILD_NUMBER'].to_s.rjust(3, '0') %>
    build: <%= ENV['BUILD_NUMBER'] %>
    sha: <%= (ENV['BUILD_VCS_NUMBER'] || `git rev-parse --short HEAD`)[0...7] %>

client:
  shell_transscripts: <%= Gem.win_platform? ? 'C:\Cygwin\tmp\screen*.log' : File.join(ENV['HOME'], '*zsh*.log') %>
  log:
    level: Trace

deployment:
  canoncial_url: http://localhost:34530/

web:
  bindings:
    -
      :protocol: http
      :host: localhost
      :port: 34530
    -
      :protocol: http
      :host: watchr.dev
