project: Watchr

build:
  configuration: Debug
  number: <%= ENV['BUILD_NUMBER'] %>
  sha: <%= (ENV['BUILD_VCS_NUMBER'] || `git rev-parse --short HEAD`)[0...7] %>

deployment:
  connection:
    computer_name: localhost
    username: <%= ENV['DEPLOY_USER'] %>
    password: <%= ENV['DEPLOY_PASSWORD'] %>

  remote_path: <%= (File.expand_path(ENV['TEMP'] || '', '_watchr')) %>
  canoncial_url: http://localhost:34530/

  bindings:
    -
      :protocol: http
      :host: localhost
      :port: 34530
    -
      :protocol: http
      :host: watchr.dev
      :test_while_deployment: false
