build:
  configuration: Release
  metadata:
    pre:

deployment:
  canoncial_url: https://watch.grossweber.com/

client:
  log:
    level: Warn

web:
  bindings:
    -
      :protocol: https
      :host: watch.grossweber.com
    -
      :protocol: http
      :host: watch.grossweber.com
