build:
  configuration: Release

deployment:
  connection:
    computer_name: watch.grossweber.com

  remote_path: C:/GROSSWEBER/watch
  canoncial_url: http://watch.grossweber.com/

  bindings:
    -
      :protocol: http
      :host: watch.grossweber.com
