build:
  configuration: Release
  metadata:
    pre:

deployment:
  canoncial_url: http://watch.grossweber.com/

web:
  bindings:
    -
      :protocol: http
      :host: watch.grossweber.com
